name: Kotlin CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Coverage
    runs-on: ubuntu-22.04

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer JDK 21
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # Étape 3 : Rendre gradlew exécutable
      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      # Étape 4 : Construire et tester l'application avec JaCoCo
      - name: Build, Test, and Generate Coverage Report
        run: ./gradlew clean test jacocoTestReport

      # Étape 5 : Publier le rapport JaCoCo HTML
      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test/html/

      # Étape 6 : Publier le rapport JaCoCo XML (Optionnel)
      - name: Upload JaCoCo XML Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml
