name: Kotlin CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test, Coverage, and Static Analysis
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 21
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # 3. Make gradlew executable
      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      # 4. Run build, tests (including coverage), and static analysis
      - name: Build, Test, Coverage and Static Analysis
        run: ./gradlew clean build --refresh-dependencies

      # 5. Upload JaCoCo HTML report
      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html/

      # 6. Upload JaCoCo XML report
      - name: Upload JaCoCo XML Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

      # 7. Upload Detekt report
      - name: Upload Detekt Report
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: build/reports/detekt/detekt.xml
